<?php

/**
 * Returns themed content for each element
 */
function gsb_feature_program_finder_display_preprocess_program_isotope_item(&$variables) {

}
function gsb_feature_program_finder_display_preprocess_program_isotope_degree_item(&$variables) {

}
function gsb_feature_program_finder_display_preprocess_program_isotope_item_wrapper(&$variables) {

}
function gsb_feature_program_finder_display_preprocess_faculty_isotope_item(&$variables) {

}